apiVersion: batch/v1
kind: Job
metadata:
  name: curl-job
spec:
  template:
    spec:
      containers:
          - name: curl-job
            image: curlimages/curl:7.83.1            
            args:
            - /bin/sh
            - -c
            - curl https://kubernetes.io/pt-br/
      restartPolicy: Never
  backoffLimit: 4